/run/numberOfThreads 1
/run/verbose 2
/run/initialize

#optical photon source
/gps/particle opticalphoton

#point source within scint
/gps/pos/type Point
/gps/pos/centre 0 0 0 mm

#emit photons isotropically
/gps/ang/type iso
/gps/polarization 0 0 0

#set photon energy
/gps/ene/type Arb
/gps/ene/emspec true
/gps/ene/diffspec true

/gps/hist/type Arb
/gps/hist/file emission_gps.dat
/gps/hist/inter Lin

#run 78,883 photons for 1461 keV full energy event
/run/beamOn 78883